version: '3.4'

services:
  rtmpnodeserver:
    image: rtmpnodeserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 19350:19350
